### ISSUE TITLE
Add brief headline for speakers

### ISSUE THREAD

**Issue by ananyacleetus** [ReflectionsProjections/ReflectionsProjections.github.io#15]
I think that'd be more effective than just the names

**Comment by PradyumnaShome** [comment]
Do you mean something like?

## Richard Stallman
_"It's FOSS or nothing"_

**Comment by ananyacleetus** [comment]
I meant more like a bio headline

**Comment by PradyumnaShome** [comment]
Oh, so more info about each speaker, and not about the talk. Actually, this idea was proposed to @vidushirai , but was deemed unnecessary.

**Comment by PradyumnaShome** [comment]
The previous iteration of the site had bios, but after a discussion, we came to a consensus that sponsors would mostly be concerned about the names/profiles of speakers but I guess it's still open for debate.

**Comment by WalisWang** [comment]
@PradyumnaShome Instead of putting years under the names of speakers, we put single line bios for the speakers. It is something like "Anna Patterson --Vice President of Engineering, Artificial Intelligence at Google", which is just a major title(s) for each speaker. The bios from last years are too long, for this year, we just add brief bios to them.  I have asked Vibhav to search for the bios for the speakers. You can work on this issue together with him if you have time.

**Comment by PradyumnaShome** [comment]
Makes sense. It should just be a matter of replacing the date field with the bios.
